[package]
name = "win-sys"
version = "0.1.0"
edition = "2024"
resolver = "3"
description = "Windows-specific system utilities for overlay management"

[dependencies]
# Windows API bindings
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_System_Threading",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_LibraryLoader",
    "Win32_System_Console",
    "Win32_UI_Shell",
    "Win32_Security",
    "Win32_System_SystemServices",
] }

anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0.219", features = ["derive"] }

[target.'cfg(windows)'.dependencies]
# Additional Windows-specific dependencies if needed
winapi = { version = "0.3", features = [
    "winuser",
    "wingdi",
    "processthreadsapi",
    "handleapi",
    "errhandlingapi",
] }
