[workspace]
resolver = "3"
members = [
    "winapp/src-tauri",
    "packages/win-sys",
    "packages/payments",
    "packages/learning", 
    "packages/windows"
]

[workspace.dependencies]
win-sys = { path = "packages/win-sys" }
