[package]
name = "learning"
version = "0.1.0"
edition = "2021"

[dependencies]
postgrest = "1.6.0"
# OCR dependencies
tesseract = "0.8.0"
image = "0.24"
# Audio transcription dependencies
cpal = "0.15"
hound = "3.5"
# Local LLM dependencies
tokenizers = "0.15"
rust-bert = "0.21"
tch = "0.13"
# General utilities
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
futures = "0.3"
regex = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
