[package]
name = "payments"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stripe = "0.28"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
