[package]
name = "payments"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stripe = "0.28"
tokio = { version = "1.0", features = ["full", "sync"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4"
rand = "0.8"
