[package]
name = "windows-service"
version = "0.1.0"
edition = "2021"

[dependencies]
# Windows service dependencies
windows-service = "0.6"
windows = { version = "0.48", features = ["Win32_Foundation", "Win32_System_Threading", "Win32_System_Services"] }

# HTTP server dependencies
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }
hyper = { version = "1.0", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Async utilities
futures = "0.3"
async-trait = "0.1"

# Signal handling for standalone mode
ctrlc = "3.4"

# Time utilities
chrono = { version = "0.4", features = ["serde"] }

# Local packages
learning = { path = "../learning" }
payments = { path = "../payments" }

# Configuration
config = "0.13"
toml = "0.8"

# UUID generation
uuid = { version = "1.0", features = ["v4", "serde"] }

# File system operations
tokio-util = "0.7"
path-slash = "0.2"

[target.'cfg(windows)'.dependencies]
windows-service = "0.6"

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs" 